language: node_js
node_js:
  - "stable"
cache: npm

install:
  - npm ci



jobs:
  include:
    - stage: Tests
      scripts: npm run test
    - stage: Build
      scripts: npm run build
    - stage: Deploy
      scripts: skip
        deploy:
          provider: pages
          skip_cleanup: true
          keep-history: true
          github_token: $GITHUB_TOKEN
          local_dir: build
          on:
            branch: master
