language: node_js
node_js:
  - stable
  - 12
  - 14
cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build
  edge:
    branch: master
